---
title: Eli Has Opinions
timezone: UTC
collections:
  associates:
    title: Associates
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: "...and you should read them!"
email: bloobop606@gmail.com
description: Eli Has Opinions is a blog for Eli Schoolar, giving his take on media
  content that has impacted his life and wants to share with the internet.
baseurl: 
url: 
twitter_username: bloobop
markdown: kramdown
remote_theme: thegoobs/eli-theme
plugins:
- jekyll-feed
- jekyll-remote-theme
